name: Hello World

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Say Hello!
        run: echo "Hello, World!"

      - name: list files
        run: ls -a
